// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.9
// source: proto/loadtest.proto

package loadtest

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message
type LoadTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumRequests   int32                  `protobuf:"varint,1,opt,name=num_requests,json=numRequests,proto3" json:"num_requests,omitempty"`
	Concurrency   int32                  `protobuf:"varint,2,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadTestRequest) Reset() {
	*x = LoadTestRequest{}
	mi := &file_proto_loadtest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTestRequest) ProtoMessage() {}

func (x *LoadTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loadtest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTestRequest.ProtoReflect.Descriptor instead.
func (*LoadTestRequest) Descriptor() ([]byte, []int) {
	return file_proto_loadtest_proto_rawDescGZIP(), []int{0}
}

func (x *LoadTestRequest) GetNumRequests() int32 {
	if x != nil {
		return x.NumRequests
	}
	return 0
}

func (x *LoadTestRequest) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *LoadTestRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

// Response message
type LoadTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount  int32                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailureCount  int32                  `protobuf:"varint,2,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	AvgLatencyMs  float64                `protobuf:"fixed64,3,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	ThroughputRps float64                `protobuf:"fixed64,4,opt,name=throughput_rps,json=throughputRps,proto3" json:"throughput_rps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadTestResponse) Reset() {
	*x = LoadTestResponse{}
	mi := &file_proto_loadtest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTestResponse) ProtoMessage() {}

func (x *LoadTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loadtest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTestResponse.ProtoReflect.Descriptor instead.
func (*LoadTestResponse) Descriptor() ([]byte, []int) {
	return file_proto_loadtest_proto_rawDescGZIP(), []int{1}
}

func (x *LoadTestResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *LoadTestResponse) GetFailureCount() int32 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *LoadTestResponse) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *LoadTestResponse) GetThroughputRps() float64 {
	if x != nil {
		return x.ThroughputRps
	}
	return 0
}

var File_proto_loadtest_proto protoreflect.FileDescriptor

const file_proto_loadtest_proto_rawDesc = "" +
	"\n" +
	"\x14proto/loadtest.proto\x12\bloadtest\"p\n" +
	"\x0fLoadTestRequest\x12!\n" +
	"\fnum_requests\x18\x01 \x01(\x05R\vnumRequests\x12 \n" +
	"\vconcurrency\x18\x02 \x01(\x05R\vconcurrency\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"\xa9\x01\n" +
	"\x10LoadTestResponse\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x05R\fsuccessCount\x12#\n" +
	"\rfailure_count\x18\x02 \x01(\x05R\ffailureCount\x12$\n" +
	"\x0eavg_latency_ms\x18\x03 \x01(\x01R\favgLatencyMs\x12%\n" +
	"\x0ethroughput_rps\x18\x04 \x01(\x01R\rthroughputRps2S\n" +
	"\x0fLoadTestService\x12@\n" +
	"\aRunTest\x12\x19.loadtest.LoadTestRequest\x1a\x1a.loadtest.LoadTestResponseB\x1bZ\x19gcf-worker/proto;loadtestb\x06proto3"

var (
	file_proto_loadtest_proto_rawDescOnce sync.Once
	file_proto_loadtest_proto_rawDescData []byte
)

func file_proto_loadtest_proto_rawDescGZIP() []byte {
	file_proto_loadtest_proto_rawDescOnce.Do(func() {
		file_proto_loadtest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_loadtest_proto_rawDesc), len(file_proto_loadtest_proto_rawDesc)))
	})
	return file_proto_loadtest_proto_rawDescData
}

var file_proto_loadtest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_loadtest_proto_goTypes = []any{
	(*LoadTestRequest)(nil),  // 0: loadtest.LoadTestRequest
	(*LoadTestResponse)(nil), // 1: loadtest.LoadTestResponse
}
var file_proto_loadtest_proto_depIdxs = []int32{
	0, // 0: loadtest.LoadTestService.RunTest:input_type -> loadtest.LoadTestRequest
	1, // 1: loadtest.LoadTestService.RunTest:output_type -> loadtest.LoadTestResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_loadtest_proto_init() }
func file_proto_loadtest_proto_init() {
	if File_proto_loadtest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_loadtest_proto_rawDesc), len(file_proto_loadtest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_loadtest_proto_goTypes,
		DependencyIndexes: file_proto_loadtest_proto_depIdxs,
		MessageInfos:      file_proto_loadtest_proto_msgTypes,
	}.Build()
	File_proto_loadtest_proto = out.File
	file_proto_loadtest_proto_goTypes = nil
	file_proto_loadtest_proto_depIdxs = nil
}
