// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.9
// source: proto/loadtest.proto

package loadtest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoadTestService_RunTest_FullMethodName = "/loadtest.LoadTestService/RunTest"
)

// LoadTestServiceClient is the client API for LoadTestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC Service
type LoadTestServiceClient interface {
	RunTest(ctx context.Context, in *LoadTestRequest, opts ...grpc.CallOption) (*LoadTestResponse, error)
}

type loadTestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoadTestServiceClient(cc grpc.ClientConnInterface) LoadTestServiceClient {
	return &loadTestServiceClient{cc}
}

func (c *loadTestServiceClient) RunTest(ctx context.Context, in *LoadTestRequest, opts ...grpc.CallOption) (*LoadTestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadTestResponse)
	err := c.cc.Invoke(ctx, LoadTestService_RunTest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoadTestServiceServer is the server API for LoadTestService service.
// All implementations must embed UnimplementedLoadTestServiceServer
// for forward compatibility.
//
// gRPC Service
type LoadTestServiceServer interface {
	RunTest(context.Context, *LoadTestRequest) (*LoadTestResponse, error)
	mustEmbedUnimplementedLoadTestServiceServer()
}

// UnimplementedLoadTestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoadTestServiceServer struct{}

func (UnimplementedLoadTestServiceServer) RunTest(context.Context, *LoadTestRequest) (*LoadTestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunTest not implemented")
}
func (UnimplementedLoadTestServiceServer) mustEmbedUnimplementedLoadTestServiceServer() {}
func (UnimplementedLoadTestServiceServer) testEmbeddedByValue()                         {}

// UnsafeLoadTestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoadTestServiceServer will
// result in compilation errors.
type UnsafeLoadTestServiceServer interface {
	mustEmbedUnimplementedLoadTestServiceServer()
}

func RegisterLoadTestServiceServer(s grpc.ServiceRegistrar, srv LoadTestServiceServer) {
	// If the following call pancis, it indicates UnimplementedLoadTestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoadTestService_ServiceDesc, srv)
}

func _LoadTestService_RunTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadTestServiceServer).RunTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadTestService_RunTest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadTestServiceServer).RunTest(ctx, req.(*LoadTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoadTestService_ServiceDesc is the grpc.ServiceDesc for LoadTestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoadTestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loadtest.LoadTestService",
	HandlerType: (*LoadTestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunTest",
			Handler:    _LoadTestService_RunTest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/loadtest.proto",
}
